### ISSUE TITLE
Bad border alignment

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#128]
```css
/* part */
level1.part h1, *[epub|type~='part'] h1 {
        border-bottom: ⠤;
        border-left: ⠇;
        border-right: ⠸;
        border-top: ⠉;
        margin-bottom: 1;
        margin-left: 1;
        margin-right: 5;
        margin-top: 2;
        text-align: center;
        text-indent: 0;
}
```

```xml
<level1 class="part">
    <h1>Part</h1>
```

```xml
<row/>
<row/>
<row>⠀⠀⠏⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠹</row>
<row>⠀⠀⠀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠠⠏⠁⠗⠞⠀⠀⠀⠀⠀⠀⠀⠀⠸⠀⠀⠀⠀⠀⠀</row>
<row>⠀⠀⠧⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠼</row>
<row/>
```
