### ISSUE TITLE
No headline for volume TOC

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#134]
the SCSS contains:

```scss
#generated-volume-toc, #generated-document-toc {
        /* ... */
        
        &::before {
            content: 'Innhold';
            display: block;
            margin-top: 2;
            margin-left: 5;
            margin-right: 5;
            margin-bottom: 1;
            text-align: center;
            border-top: ⠉;
            border-bottom: ⠉;
        }
        
        /* ... */
}
```

This seems to carry over fine to OBFL; the unicode braille representation of the "Innhold" headline is in the OBFL for both the document-toc and the volume-toc. However, in the resulting PEF, the volume-toc does not have a headline.

Test here: 2b09cb08b01e0a3f5b9317a02ad8d97c65b8eee1
