### ISSUE TITLE
Print page number is only displayed on braille pages where print page break occurs

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#141]
Reported by @matskober.

@KariRudjord what is the desired behavior? Should print page number be displayed on all pages or only on the pages where the print page break occurs?

**Comment by KariRudjord** [comment]
Print page should be displayed on all pages yes. It has worked with the books I have tested. What happens with this book I'm not sure of (561652). Maybe Bert can have a look? 


https://files.slack.com/files-pri/T08ASUYH3-F7XMRBQJZ/download/print_page_issue.zip

**Comment by josteinaj** [comment]
For reference: input files available in job 1422 and 1428.

**Comment by KariRudjord** [comment]
I'm sorry, I gave unprecice information here. The desired behavior is: print page number should be displayed on all pages i right bottom margin. But the full cell from margin that indicates page turn (123456) should not be repeated on all pages in bottom margin to the right, only when page turn from one to another in original. 

Eg. if original turns from p.4 to p.5 - on that page in braille where it happens the full cell shall stand before the page number in bottom to right. If there are no full cell in left margin, there shall not be full cell before original pagenumber down to the right.

Would that be easy to implement, @bertfrees ?

**Comment by josteinaj** [comment]
Just reproduced. Print page break is currently only displayed on the page where the print page break occurs. I assume this is just a CSS matter though, and also not really critical, so I'm changing the priority. We could maybe move it to Q1 2018 as well, there's not much left of 2017.

**Comment by bertfrees** [comment]
We currently use `string(print-page, last)` which should render `print-page` on every page. If that does not happen it's a bug.

The 123456 is currently rendered on every page because we have this rule:

```css
pagenum {
   string-set: print-page "⠿" content();
}
```

To get the desired behavior I think this should work:

```scss
@page {
   @bottom-right {
      content: string(print-page-break-indicator, first)
               string(print-page, last);
   }
}
pagenum {
   string-set: print-page content()
               print-page-break-indicator "⠿";
   &::after {
      string-set: print-page-break-indicator "";
   }
}
```

(although I'm not sure the `::after` works in combination with `display: none`.
