### ISSUE TITLE
Always break page before a part

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#144]
Reported by @matskober.

Currently:
```css
level1.part, *[epub|type~='part'] {
    page-break-before: auto;
    // ...
}
```

Should be:
```css
level1.part, *[epub|type~='part'] {
    page-break-before: right;
    // ...
}
```

**Comment by matskober** [comment]
Could it not be "page-break-before: right;" on all level1s, as a default?

**Comment by josteinaj** [comment]
@matskober yes we already do that for level1 chapters and level2 chapters within level1 parts, but not for the level1 parts themselves.

**Comment by josteinaj** [comment]
If I change the CSS as described above, then volume breaking is no longer forced. For instance, this test fails:

[with parts: parts will be top level splitting points](https://github.com/nlbdev/pipeline/blob/7a04db3e7496a81b0827a8b0d667bef41ac24a50/modules/nlb/book-to-pef/src/test/xprocspec/test_dtbook-to-pef_volume-breaking.xprocspec#L162)

@bertfrees maybe you could have a look at why this happens when you get the time.

**Comment by bertfrees** [comment]
@josteinaj It appears to be bug: https://github.com/daisy/pipeline-mod-braille/issues/173

I've created a workaround for now.

**Comment by KariRudjord** [comment]
#2043 DTBook 561894: Yes, always page break before part works - but Part 1 is on the last page in first volume. It should have been moved to volume two.

Volume 6 contains 3 pages, title page, TOC page and Part two page
  
Related to #122

**Comment by josteinaj** [comment]
@KariRudjord volume breaking always happens before parts - except for the first part. However, maybe we should make sure that there's at least a couple of pages after part 1 starts so that it's not on the last page?

We could try adding something like this:
```css
level1.part > *:first-child,
section[epub|type~='part'] > *:first-child,
body[epub|type~='part'] > *:first-child {
    -obfl-keep-with-next-sheets: 2;
}
```

...which is actually what #88 is about.
