### ISSUE TITLE
Fallback mechanism for matrix tables that can not be rendered as matrix tables

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#207]
There shouldn't be an exception if matrix tables can not be rendered as matrix tables. It should rather fall back to render as a list, and print a warning.

**Comment by bertfrees** [comment]
See also https://github.com/nlbdev/pipeline/issues/8#issuecomment-339313724.

I've done some thinking about this, and I think it would make the most sense to do something like this:

```scss
table {
  display: table;
  &::-obfl-alternate-scenario {
    display: block;
    -obfl-scenario-cost: -obfl-evaluate('...');
  }
}
```

which should translate to something like this in the OBFL:

```xml
<obfl xmlns:d="http://www.daisy.org/ns/pipeline/data"
      xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
      xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xml-processor name="take-nth">
    <xsl:stylesheet version="2.0">
      <xsl:param name="n" as="xs:integer"/>
      <xsl:template match="/">
        <xsl:sequence select="/*/d:scenario[position()=$n]"/>
      </xsl:template>
    </xsl:stylesheet>
  </xml-processor>
  <renderer name="renderer-1">
    <rendering-scenario processor="take-nth" cost="-Infinity">
      <param name="n" value="1"/>
    </rendering-scenario>
    <rendering-scenario processor="take-nth" cost="...">
      <param name="n" value="2"/>
    </rendering-scenario>
  </renderer>
  <sequence>
    ...
    <xml-data renderer="renderer-1">
      <d:scenarios>
        <d:scenario>
          <table>...</table>
        </d:scenario>
        <d:scenario>
          <block> ... </block>
        </d:scenario>
      </d:scenarios>
    </xml-data>
    ...
  </sequence>
</obfl>
```

**Comment by bertfrees** [comment]
You should now (in theory*) be able to do something like the snippet below. Can you experiment a little and come up with some good settings? Apart from `$forced-break-count` you can also use `$total-height` and `$forced-break-count`. The syntax of the OBFL evaluation language is defined [here](http://braillespecs.github.io/obfl/obfl-evaluation-language.html).

The example explains itself I think but let me know if it's unclear.

```scss
table {
    ...
    
    &%table-fallback {
        @extend %table-matrix;
        -obfl-scenario-cost: -obfl-evaluate('$forced-break-count');
        &:-obfl-alternate-scenario {
            @extend %table-as-list;
            -obfl-scenario-cost: 0; // format table as list when matrix format
                                    // results in at least 1 forced line break

        }
    }
        
    &.table-fallback {
        @extend %table-fallback;
    }
}
```

(*) I say in theory because SASS does something undesired with the order of pseudo-elements and pseudo-classes when expanding the `@extend ...;` statements (see the comments in tables.scss). In reality we need quite a bit of duplication. But that would make this example less understandable.

**Comment by bertfrees** [comment]
The SASS issue was bothering me so I fixed it. tables.scss is much simplified now. I also added a variation of the snippet above and tested that it works.

```scss
%table-fallback {
    @extend %table-matrix;
    
    // format table as list when matrix format results in at least 1 forced line break,
    // or the total height in matrix format is more than 33% larger
    -obfl-scenario-cost: -obfl-evaluate('(+ (* 10 $forced-break-count) (* .75 $total-height))');
    &:-obfl-alternate-scenario {
        @extend %table-as-list;
        -obfl-scenario-cost: -obfl-evaluate('$total-height');
    }
}
```
