### ISSUE TITLE
Include subtitle and series title on titlepage

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#212]
I think we have some CSS already for subtitle on titlepage. Would like to implement it in PIP. 
- Like main title: with rules that put the whole title in Om boka if it doesn't fit on titlepage

Would also like to include series title on titlepage.  After title and any subtitle with an empty row before series title.

**Comment by bertfrees** [comment]
I was trying to understand what needs to be done here. It seems this is all handled in insert-boilerplate.xsl which Jostein wrote and I don't understand that well what is going on. So Jostein can you take care of this alone?

By the way insert-boilerplate.xsl looks quite advanced, and it looks to me like some of it could be implemented in CSS, or it would at least be good candidates for new CSS features. Notably the line breaking stuff. At the moment there is basically no configurability for the end-user. @josteinaj if you could explain what the various functions in insert-boilerplate.xsl do exactly, I could explore this a bit more.

**Comment by josteinaj** [comment]
Yeah I can fix this issue (when I have time).

If we could do this in CSS it would be great.

So, the main stuff is in the `generate-frontmatter` template.
- first it picks out from metadata: author, full title, title, subtitle, translator, original publisher and original ISBN
- it also uses parameters, which comes from the script options, to generate text for the contraction grade and notes placement
- it tries to fit the list of authors within 3 lines
- it tries to fit the title within 5 lines
- it tries to fit the translators within 2 lines
- when handling names (authors and translators), the names are flipped around commas, so that the form is "first middle last" instead of "middle last, first"
- then the title page is laid out:
    - first 3 empty rows
    - if there's at least one author:
        - then the author is listed (up to 3 lines)
        - and 2 empty rows are inserted
    - if there's a title
        - then the title is inserted (up to 5 lines)
        - and 2 empty rows are inserted
    - if there's at least one translator:
        - add a row with "Oversatt av:" ("Translated by:")
        - list the translators (up to 2 lines)
        - and 2 empty rows are inserted
    - fill the page with empty lines so that there are just 6 rows left on the page (i.e. up until the footer)
    - add a row with "NLB - {year}"
    - add a row with the contraction grade
    - add a row with the text " av " (" of ") and the class "pef-volume", and then in the CSS the current volume and total volumes are listed before and after that, so it becomes "1 of 3" etc.
- then the about page is laid out:
    - create a headline with "Om boka" ("About the book")
    - if the authors didn't fit on the title page, list them here
    - if the full title didn't fit on the title page, list it here
    - if the translators didn't fit on the title page, list it here
    - if there are notes in the book, say how the notes are placed (footer / volumes / end of book)

If we want to try to do this with CSS, I think the main thing we would need is a function that returns how many lines in the resulting PEF a certain string or node would result in, given the width available in a certain context (i.e. consider padding, margins etc.). So, if we had this in a template:

```html
<section class="pef-titlepage">
    <p class="fulltitle">Title of my book</p>
</section>

<section class="pef-about">
    <p class="fulltitle">Title of my book</p>
</section>
```

Then we could maybe have a SCSS rule like this (probably not syntactically correct):

```scss
section.pef-titlepage p.fulltitle {
    max-height: 5; // fit as much as possible, end with "..." if cropped
}
section.pef-about p.fulltitle {
    // pef:lines are here expected to return the number of lines the fulltitle would fill
    // if it were not limited vertically by the max-height property,
    // but still limited horizontally by margins, padding etc.
    if (pef:lines(.) <= 5) {
        display: none; // only display on about page if it didn't fit on title page
    }
}
```

And for authors you could maybe do something more advanced, like:

```html
<section class="pef-titlepage">
    <div class="authors">
        <p class="author">First author</p>
        <p class="author">Second author</p>
    </div>
</section>

<section class="pef-about">
    <p class="fulltitle">Title of my book</p>
</section>
```

```scss
section.pef-titlepage div.authors {
    /* three or more authors */
    p.author {
        max-height: 1;
    }

    /* one author */
    p.author:nth-child(1):nth-last-child(1) {
        max-height: 3;
    }

    /* two authors */
    p.author:nth-child(1):nth-last-child(2), p.author:nth-child(2):nth-last-child(1) {
        max-height: 2;
    }
}

section.pef-about div.authors {
    if (pef:lines(.) <= 3) {
        display: none;
    }
}
```

**Comment by bertfrees** [comment]
What I was getting at mainly was to find a way to

- make as much functionality as possible configurable through CSS, and
- replace the parts of the XSLT code that are already implemented in other parts of the Pipeline.

New CSS features like "max-height" are also a good idea. I'm not sure about the pef:lines function and the conditionals. That might be stretching the scope of CSS a bit too much. But I agree it would be nice if we could do this in CSS too. But maybe we need to think of a more idiomatic way.

The things that can already be done in CSS are:

- Positioning a box on a specific vertical offset: the "-obfl-vertical-position" property can be used for this.
- Inserting empty lines between blocks can be done with margin or padding.
- Inserting text based on the value of contraction-grade can be done with SASS conditionals.
   ```scss
   @if $contraction-grade == 0 {
     content: 'Fullskrift';
   } @else {
     content: 'Kortskrift #{$contraction-grade}';
   }
   ```
   The `contraction-grade` variable would have to be computed in XProc because SASS doesn't have text manipulation functions (unless we would define custom functions).

New CSS features could include:

- The "max-height" property to let contents overflow the block boundaries.
- The "[text-overflow](https://quirksmode.org/css/user-interface/textoverflow.html)" property to create the ellipsis.

Things that should probably stay in XSLT are
- flipping of first/last names,
- generating the date,
- ...

I was particularly interested in what the nlb:strings-to-lines function does. What is the "break-words" parameter (never|avoid|always)? This sounds like a line breaking function, for which we should use already existing Java code I think. It would stay an XSLT function, for the time being, but it would have a Java implemention. Such an XSLT function does not exist yet but I have been thinking about adding it. The result would be a plain string with preserved newlines, rather than  a series of p elements, and it would be translated to braille, so that you don't need the nlb:braille-length function. The break-words parameter sounds like it could become a new CSS property or could be covered by the "hyphens" property.
