### ISSUE TITLE
Web UI handling of em and strong

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#217]
I would like an option that leave out strong i a production and an option that leave out em in production. E.g. under Tekstelementer. Nice to use in cooking books who always have a lot of em and strong that is only related to layout.

**Comment by josteinaj** [comment]
So two separate options? One to leave out `<em>` and one to leave out `<strong>`?

For books that don't have `<em>`, only `<strong>`, we currently treat the `<strong>` tags as if they were `<em>`. If we use the options to say that we want to leave out `<em>` but keep `<strong>`, what should happen for such books? Should we remove the `<strong>` tags in that case? If not, should they be treated as if they were `<em>` tags, even though the option to leave out `<em>` tags are enabled?

**Comment by bertfrees** [comment]
If we reconsider implementing emphasis in Liblouis instead of XSLT (https://github.com/nlbdev/pipeline-mod-nlb/issues/20), the toggling could be easily implemented in CSS. It's also easily implemented in XSLT of course, but the less XSLT code the better I think.

**Comment by josteinaj** [comment]
We'd be fine with using liblouis. Controlling it with CSS would be great. I think the issue was the ordering of the open- and close "tags" in braille. `<em><strong>…</strong></em>` vs `<strong><em>…</em></strong>` vs `<em><strong>…</em></strong>` vs `<strong><em>…</strong></em>`, which could not be controlled in liblouis.

**Comment by bertfrees** [comment]
Ah yes, indeed, this can not be controlled at the moment.

**Comment by KariRudjord** [comment]
Two separate options, yes. And if we leave out em in a production, still treat strong as em. 

I don't know how much we will use the option, but then we can controle every situation without editing the source file (which can be quite a job).

**Comment by bertfrees** [comment]
I need a name/description of the options (Norwegian).

**Comment by bertfrees** [comment]
I have made the text formatting fully configurable in CSS. For now there is no option yet but it's very easy to add. The CSS now looks like this:

```scss
/* -------------------------------------------------------------------------- */
/*                Text formatting                                             */
/* -------------------------------------------------------------------------- */

@text-transform strong {
    system: -nlb-indicators;
    open: "⠠⠄";
    close: "⠠⠄";
}

@text-transform em {
    system: -nlb-indicators;
    open: "⠆";
    close: "⠰";
}

@text-transform u {
    system: -nlb-indicators;
    open: "⠸";
    close: "⠸";
}

@text-transform strike {
    system: -nlb-indicators;
    open: "⠐⠂";
    close: "⠐⠂";
}

strong, b {
    text-transform: strong;
    :root:not(:has(em, i)) & {
        text-transform: em;
    }
}

em, i {
    text-transform: em;
}

u {
    text-transform: u;
}

strike, s {
    text-transform: strike;
}

sub {
    text-transform: -louis-emph-4;
}

sup {
    text-transform: -louis-emph-5;
}
```

As you can see there are now the text-transform values `strong`, `em`, `u` and `strike`, and they are declared with `@text-transform` rules. The `@text-transform` rule is something I was already using for SBS.

The `@text-transform` rules are interpreted in the block-translate.xsl file.

When we are ready to handle emphasis in Liblouis, we only need a very small modification in the CSS, namely `text-transform: strong` needs to become `text-transform: -louis-emph-1`, etc.

**Comment by KariRudjord** [comment]
Name of options:
First option em: 
Inkluder em.
Når boksen er tom, blir em utelatt fra produksjonen.

Second option strong: 
Inkluder strong.
Når boksen er tom, vil strong bli utelatt fra produksjonen.

Description: For both options (don't need to be numbered in GUI) there will be a cheked box as standard, and if you uncheck the box, the em (or strong) will be left out of the production.

I think the right place to put these options is under "Tekstelementer".

**Comment by bertfrees** [comment]
Updated the CSS to the following. Hope I got it right.

```scss
@if ($include-strong) {
    strong, b {
        @if ($include-em) {
            text-transform: strong;
            :root:not(:has(em, i)) & {
                text-transform: em;
            }
        } @else {
            text-transform: em;
        }
    }
}

@if ($include-em) {
    em, i {
        text-transform: em;
    }
}
```
