### ISSUE TITLE
CSS: hide halftitlepage (frontmatter)

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#219]
To be put into NLB-CSS: setion epub:type="frontmatter halftitlepage" is repeating the title in a new page in productions. Please add to CSS that halftitlepage should be hidden in productions.

To be put into NLB-CSS: `<section id="d6e341" epub:type="frontmatter copyright-page">` shall placed in back of the book (just like colophon).

**Comment by bertfrees** [comment]
An example of a halftitlepage would be nice. I can't find any in the tests.

So basically there should just be a rule that completely hides sections with epub:type="frontmatter halftitlepage"? Is that correct?

```scss
[epub|type~='frontmatter'][epub|type~='halftitlepage'] {
  display: none;
}
```
